version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/hello-world-api
hooks:
  BeforeInstall:
    - location: chmod +x /var/www/hello-world-api/scripts/install_dependencies.sh
    - location: chmod +x /var/www/hhello-world-api/scripts/start_server.sh
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
